import { createEffect, createMemo, createSignal, onCleanup } from "solid-js"
import { createSessionSpend } from "../../session-spend"
import type { SessionMessageAssistant } from "../../engine-types"
import { createClient, createHarnessClient } from "../../client"
import { STORAGE_KEYS, readStorage, writeStorage } from "../../storage"
import { contextFigures } from "../../metrics"
import {
  SUGGESTION_SESSION_TTL,
  SUGGESTION_SYSTEM,
  buildSuggestionPrompt,
  cleanSuggestion,
  isSuggestionSession,
  pickSuggestionModel,
} from "../../reply-suggestion"
import { recordPrompt } from "../../prompt-history"
import { modelSwitchWarningOn, needsModelSwitchWarning } from "../../model-switch"
import { hasModel, replacementModel } from "../../model-catalog"
import { CHAT_PERMISSION, CHAT_SYSTEM, COWORK_AGENT, COWORK_SYSTEM } from "../../chat"
import { messageID } from "../../ids"
import type { Delivery } from "../../pending-prompts"
import { sendPrompt } from "./send"
import { chipRefs, resolveChips, withChips, type ContextChip } from "../../context-chip"
import type { Attachment, CommandOption, Workflow, StashedPrompt, ContextPack } from "../../types"
import { UNAVAILABLE_FEATURES } from "../../features"
import { BUILTIN_COMMANDS, builtinCommand, runBuiltin, type CommandContext } from "../../commands"
import { t } from "../../i18n"
import { toast } from "../../toast"
import { permissionMode } from "../../permission-modes"
import { closeTab, cycleTab } from "../../tabs"
import { skillifyPrompt } from "../../skillify"
import { resumePrompt } from "../../resume"
import type { AppStores } from "../../app-context"

export function createComposer(app: AppStores) {
  const [prompt, setPrompt] = createSignal("")
  const [agent, setAgent] = createSignal(readStorage(STORAGE_KEYS.agent, "plan"))
  const [permissionModeId, setPermissionModeId] = createSignal(readStorage(STORAGE_KEYS.permissionMode, "auto"))
  // Steering is the engine's own default, so a prompt sent mid-turn redirects the work in flight
  // unless the reader says to wait; see DeliveryMenu.
  const [delivery, setDelivery] = createSignal<Delivery>(readStorage<Delivery>(STORAGE_KEYS.delivery, "steer"))
  const changeDelivery = (value: Delivery) => {
    setDelivery(value)
    writeStorage(STORAGE_KEYS.delivery, value)
  }
  const [modelRef, setModelRef] = createSignal<{ providerID: string; id: string; variant?: string } | undefined>(
    readStorage<{ providerID: string; id: string; variant?: string } | undefined>(
      STORAGE_KEYS.selectedModel,
      undefined,
    ),
  )
  const [pendingModelSwitch, setPendingModelSwitch] = createSignal<{
    from: string
    to: string
    next: { providerID: string; id: string }
  }>()
  const [attachments, setAttachments] = createSignal<Attachment[]>([])
  // What the reader pointed at: a file, an artifact, a diff hunk, a terminal selection, a failing
  // check or a preview annotation (BU-06, UX-05). Resolved into the message only when it goes, so it
  // can be removed until then.
  const [chips, setChips] = createSignal<ContextChip[]>([])
  // Filled from the harness server by the sessions store (H-18): a stash kept in the browser was
  // neither durable nor visible on the phone.
  const [stashes, setStashes] = createSignal<StashedPrompt[]>([])
  // The refs of a draft being saved as a context pack (H-26): set when the composer asks, cleared
  // once the name dialog answers.
  const [packRefs, setPackRefs] = createSignal<string[] | undefined>()

  const [packs, setPacks] = createSignal<ContextPack[]>([])
  /**
   * The model the selected session is cached for: what the engine reuses on the next turn. It is
   * stored on the session when this app switches it, and older sessions only say it on their answers.
   */
  const sessionModel = (): { providerID: string; id: string } | undefined => {
    const stored = app.sessions.selectedSession()?.model
    if (stored) return stored
    const list = app.sessions.activeMessages() ?? []
    for (let index = list.length - 1; index >= 0; index--) {
      const message = list[index]
      if (message?.type === "assistant") return (message as SessionMessageAssistant).model
    }
    return undefined
  }
  // Suggested next message (greyed in the input, Tab accepts), generated by a small model after
  // each finished turn. See reply-suggestion.ts and client.suggest.
  const [suggestionsOn, setSuggestionsOn] = createSignal(readStorage(STORAGE_KEYS.replySuggestions, true))
  const [suggestion, setSuggestion] = createSignal<{ sessionID: string; text: string }>()
  const [suggestionModel, setSuggestionModel] = createSignal(readStorage(STORAGE_KEYS.suggestionModel, ""))
  const [suggestionEffort, setSuggestionEffort] = createSignal(readStorage(STORAGE_KEYS.suggestionEffort, ""))
  // The effort levels the chosen suggestion model offers. The automatic small model is resolved at
  // request time, so it has no catalog entry here and no effort to pick.
  const suggestionVariants = () => {
    const chosen = suggestionModel()
    const slash = chosen.indexOf("/")
    if (slash <= 0) return []
    return (
      app.catalog
        .modelList()
        .find((model) => model.providerID === chosen.slice(0, slash) && model.id === chosen.slice(slash + 1))
        ?.variants ?? []
    )
  }
  // A stored level the chosen model does not offer would be rejected by the engine, so it is dropped.
  const suggestionVariant = () =>
    suggestionVariants().some((variant) => variant.id === suggestionEffort()) ? suggestionEffort() : ""
  let suggestedFor: string | undefined
  let suggestionRun = 0
  createEffect(() => {
    const sessionID = app.sessions.selected()
    // Only prompts and answers matter; model switches and other markers are skipped.
    const list = (app.sessions.activeMessages() ?? []).filter(
      (message) => message.type === "user" || message.type === "assistant",
    )
    const last = list[list.length - 1]
    if (!sessionID || app.sessions.generating() || !suggestionsOn() || app.settings.mobileRemote() || prompt()) {
      if (app.sessions.generating() || !sessionID) setSuggestion(undefined)
      return
    }
    if (!last || last.type !== "assistant" || last.id === suggestedFor) return
    if (app.sessions.permissionData.length > 0 || app.sessions.questionData.length > 0) return
    let userIndex = list.length - 1
    while (userIndex >= 0 && list[userIndex]?.type !== "user") userIndex--
    const userText = ((list[userIndex] as { text?: string } | undefined)?.text ?? "").trim()
    const assistantText = list
      .slice(userIndex + 1)
      .flatMap((message) => (message.type === "assistant" ? (message as SessionMessageAssistant).content : []))
      .flatMap((part) => (part.type === "text" ? [(part as { text?: string }).text ?? ""] : []))
      .join("\n")
      .trim()
    if (!userText || !assistantText) return
    const lastID = last.id
    const directory = app.sessions.selectedSession()?.location?.directory
    const timer = setTimeout(() => {
      suggestedFor = lastID
      const run = ++suggestionRun
      void (async () => {
        const client = createClient(app.connection.serverUrl())
        // A model picked in Settings wins; otherwise the configured or a cheap small model.
        const chosen = suggestionModel()
        const slash = chosen.indexOf("/")
        const model =
          slash > 0
            ? {
                providerID: chosen.slice(0, slash),
                id: chosen.slice(slash + 1),
                ...(suggestionVariant() ? { variant: suggestionVariant() } : {}),
              }
            : pickSuggestionModel(
                await client.suggest.smallModel().catch(() => undefined),
                modelRef(),
                app.catalog.modelList(),
              )
        if (!model) return
        const raw = await client.suggest
          .reply({
            parentID: sessionID,
            directory,
            model,
            system: SUGGESTION_SYSTEM,
            prompt: buildSuggestionPrompt(userText, assistantText),
          })
          .catch(() => undefined)
        const text = cleanSuggestion(raw)
        if (
          !text ||
          run !== suggestionRun ||
          app.sessions.selected() !== sessionID ||
          prompt() ||
          app.sessions.generating()
        )
          return
        setSuggestion({ sessionID, text })
      })()
    }, 800)
    onCleanup(() => clearTimeout(timer))
  })
  const currentSuggestion = () => {
    const value = suggestion()
    return value && value.sessionID === app.sessions.selected() && !prompt() ? value.text : undefined
  }
  const toggleSuggestions = () => {
    const next = !suggestionsOn()
    setSuggestionsOn(next)
    writeStorage(STORAGE_KEYS.replySuggestions, next)
    if (!next) setSuggestion(undefined)
  }
  // What the open session spent (UL-06), from the ledger: the composer's turn and session figures.
  const sessionSpend = createSessionSpend(() => {
    const sessionID = app.sessions.selected()
    if (!sessionID || !app.runs.routinesServerAvailable()) return undefined
    return { serverUrl: app.connection.harnessServerUrl(), sessionID, messages: app.sessions.activeMessages() ?? [] }
  })
  const contextUsage = () =>
    contextFigures(
      app.sessions.selectedSession(),
      app.sessions.activeMessages() ?? [],
      currentModel(),
      app.catalog.engineConfig()?.compaction,
    )

  // A tab closed while a suggestion ran leaves its session behind: delete those once they are stale.
  const removedSuggestions = new Set<string>()
  createEffect(() => {
    if (!app.connection.ready()) return
    const stale = [...(app.sessions.sessions()?.data ?? []), ...(app.sessions.children()?.data ?? [])].filter(
      (session) =>
        isSuggestionSession(session) &&
        Date.now() - session.time.created > SUGGESTION_SESSION_TTL &&
        !removedSuggestions.has(session.id),
    )
    if (stale.length === 0) return
    const current = createClient(app.connection.serverUrl())
    for (const session of stale) {
      removedSuggestions.add(session.id)
      void current.session.remove({ sessionID: session.id }).catch(() => undefined)
    }
  })

  const commandOptions = (): CommandOption[] => [
    ...BUILTIN_COMMANDS.filter((command) => app.settings.desktopWindow() || !command.desktop).map((command) => ({
      name: command.id,
      description: t(command.title),
      // An action that acts on the open session is not offered when there is none.
      disabled: UNAVAILABLE_FEATURES.has(command.id) || (command.session === true && !app.sessions.selected()),
      source: "builtin" as const,
      group: t(command.group),
    })),
    // A chat has no project behind it, so the engine's commands, its skills and its workflows are
    // not offered there: what is typed after a built-in is a message, as it has always been.
    ...(app.sessions.chatView()
      ? []
      : [
          ...(app.catalog.commands()?.data ?? []).map((command) => ({
            name: command.name,
            description: command.description,
            source: "command" as const,
            group: t("Commands"),
          })),
          ...(app.catalog.skills()?.data ?? []).map((skill) => ({
            name: skill.name,
            description: skill.description ?? "Skill",
            source: "skill" as const,
            group: t("Skills"),
          })),
          // A workflow is a command: that is the audit's "launcher unificado", and the reason it
          // goes in the same list rather than a menu of its own.
          ...(app.runs.workflows() ?? []).map((workflow) => ({
            name: workflow.name,
            description: workflow.description || t("Workflow"),
            source: "workflow" as const,
            group: t("Workflows"),
          })),
        ]),
  ]

  const pastes = new Map<string, string>()

  const collapsePaste = (raw: string) => {
    const lines = raw.split("\n").length
    const token = `[Pasted ~${lines} lines]`
    pastes.set(token, raw)
    return token
  }

  const expandPastes = (value: string) => {
    let result = value
    for (const [token, full] of pastes) result = result.split(token).join(full)
    return result
  }

  const searchFiles = async (query: string) => {
    const response = await createClient(app.connection.serverUrl()).file.find({ query, limit: 8 })
    return response.data
  }

  // A built-in runs here exactly as it does typed in the composer (TI-13); anything else is put in
  // the composer for its arguments.
  const runCommand = (name: string) => {
    if (runBuiltin(name, "", commandContext())) return
    setPrompt(`/${name} `)
  }

  // A stored effort level the model does not offer here (another model's, or one this project's engine
  // lacks) is dropped: the engine rejects unknown levels, and the menu would show a level it cannot set.
  const selectedModel = () => {
    const ref = modelRef()
    if (!ref?.variant || variants().some((variant) => variant.id === ref.variant)) return ref
    return { providerID: ref.providerID, id: ref.id }
  }
  const modelKey = () => {
    const ref = selectedModel()
    return ref ? `${ref.providerID}/${ref.id}` : undefined
  }
  const currentModel = () => {
    const ref = modelRef()
    if (!ref) return
    return app.catalog.modelList().find((model) => model.providerID === ref.providerID && model.id === ref.id)
  }
  const variants = () => currentModel()?.variants ?? []
  const variantKey = () => selectedModel()?.variant

  /**
   * A session carries the model the engine reuses on its next turn. When the catalog drops it that
   * turn fails with "Model unavailable", so say which one is gone and offer the closest live model
   * of the same provider.
   */
  const missingModel = createMemo(() => {
    const ref = app.sessions.selectedSession()?.model
    if (!ref || app.catalog.modelList().length === 0 || hasModel(app.catalog.modelList(), ref)) return
    return ref
  })
  const missingModelReplacement = createMemo(() => {
    const ref = missingModel()
    return ref ? replacementModel(ref, app.catalog.modelList()) : undefined
  })

  // The dock and Customize name the model of the open session, which is the one the engine will
  // reuse: an older session, or one switched on another device, is not on the app's last pick.
  // Adopted once per open, so a switch already on its way to the engine is never undone.
  let syncedSession: string | undefined
  createEffect(() => {
    const session = app.sessions.selectedSession()
    if (!session) {
      syncedSession = undefined
      return
    }
    if (session.id === syncedSession) return
    syncedSession = session.id
    const stored = session.model
    if (!stored) return
    setModelRef({ providerID: stored.providerID, id: stored.id, variant: stored.variant })
  })

  createEffect(() => {
    if (modelRef()) return
    const preferred = Object.entries(app.catalog.modelDirectory()?.default ?? {}).find(([providerID, id]) =>
      app.catalog.modelList().some((model) => model.providerID === providerID && model.id === id),
    )
    const fallback = preferred ? { providerID: preferred[0], id: preferred[1] } : app.catalog.modelList()[0]
    if (!fallback) return
    setModelRef({ providerID: fallback.providerID, id: fallback.id })
  })

  createEffect(() => {
    const ref = modelRef()
    if (ref) writeStorage(STORAGE_KEYS.selectedModel, ref)
  })

  const modelLabel = () => {
    const model = currentModel()
    if (model) return model.name
    // A ref the catalog no longer serves has no name to show, and saying "Default model" would hide
    // which one is gone. Before the first list arrives, keep the generic label instead of an id.
    if (app.catalog.modelList().length === 0) return t("Default model")
    return modelRef()?.id ?? t("Default model")
  }
  const modelName = (ref: { providerID: string; id: string }) =>
    app.catalog.modelList().find((entry) => entry.providerID === ref.providerID && entry.id === ref.id)?.name ?? ref.id

  /** Makes the picked model the app's, and the open session's when there is one. */
  const applyModel = (providerID: string, id: string) => {
    setModelRef({ providerID, id })
    const sessionID = app.sessions.selected()
    if (!sessionID) return
    void app.sessions.run(async (current) => {
      await current.session.switchModel({ sessionID, model: { id, providerID } })
      return undefined
    })
  }

  /**
   * A session that already holds context is cached for its model, so moving it to another one makes
   * the new model re-read the whole transcript: ask first, naming both. Nothing else needs asking.
   */
  const requestModel = (providerID: string, id: string) => {
    const current = sessionModel()
    if (
      current &&
      needsModelSwitchWarning({
        enabled: modelSwitchWarningOn(),
        history: (app.sessions.activeMessages() ?? []).length > 0,
        current,
        next: { providerID, id },
      })
    ) {
      setPendingModelSwitch({
        from: modelName(current),
        to: modelName({ providerID, id }),
        next: { providerID, id },
      })
      return
    }
    applyModel(providerID, id)
  }

  const pickModel = (providerID: string, id: string) => {
    app.router.setModelPickerOpen(false)
    requestModel(providerID, id)
  }

  const changeModel = (key: string) => {
    const [providerID, ...rest] = key.split("/")
    const id = rest.join("/")
    if (!providerID || !id) return
    requestModel(providerID, id)
  }

  const changeVariant = (value: string) => {
    const ref = modelRef()
    if (!ref) return
    const next = { providerID: ref.providerID, id: ref.id, variant: value || undefined }
    setModelRef(next)
    const sessionID = app.sessions.selected()
    if (!sessionID) return
    void app.sessions.run(async (current) => {
      await current.session.switchModel({
        sessionID,
        model: { id: next.id, providerID: next.providerID, ...(next.variant ? { variant: next.variant } : {}) },
      })
      return undefined
    })
  }

  const readAttachments = (files: File[]) =>
    Promise.all(
      files.map(
        (file) =>
          new Promise<Attachment>((resolve) => {
            const reader = new FileReader()
            reader.onload = () => resolve({ uri: String(reader.result), name: file.name })
            reader.onerror = () => resolve({ uri: "", name: file.name })
            reader.readAsDataURL(file)
          }),
      ),
    ).then((items) => items.filter((item) => item.uri))

  const addAttachments = (files: File[]) => {
    void Promise.all(
      files.map(
        (file) =>
          new Promise<Attachment>((resolve) => {
            const reader = new FileReader()
            reader.onload = () => resolve({ uri: String(reader.result), name: file.name })
            reader.onerror = () => resolve({ uri: "", name: file.name })
            reader.readAsDataURL(file)
          }),
      ),
    ).then((items) => setAttachments((list) => [...list, ...items.filter((item) => item.uri)]))
  }

  const removeAttachment = (uri: string) => {
    setAttachments((list) => list.filter((item) => item.uri !== uri))
  }

  // The stash lives on the harness server (H-18), so it is the same list on every device. The
  // stream event adds it back; this only asks and, once it answers, shows it.
  const stashPrompt = (text: string, clear: boolean) => {
    const value = text.trim()
    if (!value) {
      toast(t("No prompt to save"), "info")
      return
    }
    void createHarnessClient(app.connection.harnessServerUrl())
      .stash.add(value)
      .then((prompt) => {
        setStashes((list) => [prompt, ...list])
        if (clear) setPrompt("")
        toast(t("Prompt saved"), "success")
      })
      .catch((cause) => toast(cause instanceof Error ? cause.message : String(cause), "error"))
  }

  const restoreStash = (id: string) => {
    const item = stashes().find((entry) => entry.id === id)
    if (!item) return
    setPrompt(item.text)
    removeStash(id)
    app.router.setStashOpen(false)
  }

  const removeStash = (id: string) => {
    setStashes((list) => list.filter((entry) => entry.id !== id))
    void createHarnessClient(app.connection.harnessServerUrl())
      .stash.remove(id)
      .catch((cause) => toast(cause instanceof Error ? cause.message : String(cause), "error"))
  }

  // A context pack (H-26): the refs a draft already mentions, saved under a name so they can be
  // pulled back with one `@`.
  const savePack = (name: string) => {
    const refs = packRefs()
    setPackRefs(undefined)
    const trimmed = name.trim()
    if (!refs || refs.length === 0 || !trimmed) return
    const directory = app.sessions.vcsDirectory()
    void createHarnessClient(app.connection.harnessServerUrl())
      .packs.save({ name: trimmed, refs, ...(directory ? { directory } : {}) })
      .then((pack) => {
        setPacks((current) =>
          [...current.filter((entry) => entry.name !== pack.name), pack].sort((left, right) =>
            left.name.localeCompare(right.name),
          ),
        )
        toast(t("Pack saved"), "success")
      })
      .catch((cause) => toast(cause instanceof Error ? cause.message : String(cause), "error"))
  }

  const changeAgent = (value: string) => {
    setAgent(value)
    writeStorage(STORAGE_KEYS.agent, value)
    const sessionID = app.sessions.selected()
    if (!sessionID) return
    void app.sessions.run(async (current) => {
      await current.session.switchAgent({ sessionID, agent: value })
      return undefined
    })
  }

  const applyPermissionMode = async (sessionID: string, directory?: string) => {
    await app.connection.client().session.setPermission({
      sessionID,
      permission: permissionMode(permissionModeId()).rules,
      directory,
    })
  }

  const changePermissionMode = (id: string) => {
    setPermissionModeId(id)
    writeStorage(STORAGE_KEYS.permissionMode, id)
    const sessionID = app.sessions.selected()
    if (!sessionID) return
    void applyPermissionMode(sessionID, app.sessions.selectedSession()?.location?.directory).catch((cause) =>
      toast(cause instanceof Error ? cause.message : String(cause), "error"),
    )
  }

  /**
   * The chips as the engine gets them (UX-05): files and artifacts asked of the harness, which applies
   * the rules a run's packs follow, and the rest quoted. A chip that cannot be found is marked and the
   * message does not go; one that was cut is marked and goes.
   */
  const resolvePointed = async (pointed: ContextChip[], directory: string | undefined) => {
    const refs = chipRefs(pointed)
    // Over remote control the phone's scope does not reach the resolver: refs go as text, as typed
    // ones always did. So does an older harness without the route.
    const resolved =
      refs.length > 0 && app.connection.supports("context-chips") && !app.settings.mobileRemote()
        ? await createHarnessClient(app.connection.harnessServerUrl()).context.resolve({
            refs,
            ...(directory && pointed.some((chip) => chip.type === "file") ? { directory } : {}),
          })
        : undefined
    const result = resolveChips(pointed, resolved)
    if (resolved) markChips(pointed, result.missing, result.cut)
    if (result.missing.length > 0) throw new Error(t("Something you pointed at can no longer be found. Remove it to send."))
    return result
  }

  const markChips = (checked: ContextChip[], missing: string[], cut: string[]) =>
    setChips((list) =>
      list.map((chip) => {
        if (!checked.some((entry) => entry.id === chip.id)) return chip
        const problem = missing.includes(chip.id) ? "missing" : cut.includes(chip.id) ? "cut" : undefined
        if (problem) return { ...chip, problem }
        // A file that is back, or an artifact that was found this time, is no longer missing.
        return chip.problem === "missing" ? { ...chip, problem: undefined } : chip
      }),
    )

  /** A chip pointing at a file or an artifact is checked as it arrives, so the reader sees a gone one at once. */
  const addChips = (added: ContextChip[]) => {
    const known = new Set(chipRefs(chips()))
    const fresh = added.filter(
      (chip) => !((chip.type === "file" || chip.type === "artifact") && known.has(chip.ref)),
    )
    if (fresh.length === 0) return
    setChips((list) => [...list, ...fresh])
    const refs = chipRefs(fresh)
    if (refs.length === 0 || !app.connection.supports("context-chips") || app.settings.mobileRemote()) return
    const directory = app.sessions.targetDirectory() ?? app.sessions.selectedSession()?.location?.directory
    void createHarnessClient(app.connection.harnessServerUrl())
      .context.resolve({ refs, ...(directory && fresh.some((chip) => chip.type === "file") ? { directory } : {}) })
      .then((resolved) => {
        const result = resolveChips(fresh, resolved)
        markChips(fresh, result.missing, result.cut)
      })
      .catch(() => undefined)
  }

  // Chats have no commands or shell: everything typed is the message.
  const sendChat = (text: string, files: Attachment[], keepDraft = false) => {
    const pointed = chips()
    const directory = app.connection.chatsDirectory()
    if (!directory) {
      app.sessions.setError(t("Chats are not available: the engine did not report its folders"))
      return
    }
    void app.sessions.run(async (current) => {
      const resolved = await resolvePointed(pointed, undefined)
      const model = selectedModel()
      const existing = app.sessions.selected()
      const sessionID =
        existing ?? (await current.session.create({ ...(model ? { model } : {}), location: { directory } })).id
      if (!existing) {
        await current.session.setPermission({ sessionID, permission: CHAT_PERMISSION, directory })
      }
      // Same as Code: a line sent while the chat is answering interrupts it and starts a turn of
      // its own, so the answer is about this line rather than the one in flight.
      await sendPrompt(current, {
        chat: true,
        interrupt: app.sessions.generating(),
        sessionID,
        directory,
        text,
        body: withChips(expandPastes(text), resolved.text),
        files: [...files, ...resolved.files],
        model,
        instructions: app.workspace.instructionsFor(CHAT_SYSTEM),
        onReady: () => app.sessions.forgetRun(sessionID),
      })
      app.sessions.setStreamedChars(0)
      if (!keepDraft) {
        setPrompt("")
        setAttachments([])
        setChips([])
      }
      return sessionID
    })
  }

  /** Sends a prompt to the selected session (or a new one); the composer is cleared unless the draft is kept. */
  const submitPrompt = (
    text: string,
    files: Attachment[],
    keepDraft = false,
    options?: { agent?: string; system?: string },
  ) => {
    // Delivery only means something when a turn is already running; an idle session starts one.
    const mode = app.sessions.generating() ? delivery() : undefined
    // The engine delivers prompts itself (V2-41): its inbox holds a queued one, and a steer joins the
    // running execution at its next boundary with nothing to stop first.
    const id = messageID()
    // Cowork overrides the app's agent and adds its system prompt; Code sends neither.
    const promptAgent = options?.agent ?? agent()
    const pointed = chips()
    void app.sessions.run(async (current) => {
      const location = app.sessions.targetDirectory()
      // Before the session exists: a message that cannot go should not leave an empty one behind.
      const resolved = await resolvePointed(pointed, location ?? app.sessions.selectedSession()?.location?.directory)
      const model = selectedModel()
      const existing = app.sessions.selected()
      const sessionID =
        existing ??
        (
          await current.session.create({
            agent: promptAgent,
            ...(model ? { model } : {}),
            ...(location ? { location: { directory: location } } : {}),
          })
        ).id
      // No rename here: the engine's title agent names a session on its first turn, but only while
      // the title is still the placeholder it was created with. Naming it from the prompt looked
      // tidy and permanently stopped the engine from ever naming anything. See session-title.ts.
      if (!existing && !location) {
        app.sessions.setNoFolderSessions((list) => (list.includes(sessionID) ? list : [...list, sessionID]))
      }
      const listedDirectory = location ?? app.sessions.selectedSession()?.location?.directory
      await sendPrompt(current, {
        id,
        sessionID,
        // The folder this session lives in: the list is one page, so a session opened from the
        // palette has no row here and the remembered folder is the only one there is.
        directory: listedDirectory ?? app.sessions.sessionDirectories.get(sessionID),
        text,
        body: withChips(expandPastes(text), resolved.text),
        files: [...files, ...resolved.files],
        model,
        agent: promptAgent,
        instructions: app.workspace.instructionsFor(options?.system),
        permission: permissionMode(permissionModeId()).rules,
        permissionDirectory: listedDirectory,
        delivery: mode,
        onReady: () => app.sessions.forgetRun(sessionID),
        onListed: () => {
          app.sessions.setStreamedChars(0)
          if (keepDraft) return
          setPrompt("")
          setAttachments([])
          setChips([])
        },
        // A first turn that never reached the engine (an engine that does not know the agent, a
        // refused model) would otherwise leave an empty session in the list. Drop the one this
        // send just created; the reader is left with the error, not an orphan row.
        onFailed: async () => {
          if (!existing) await current.session.remove({ sessionID }).catch(() => {})
        },
      })
      return sessionID
    })
  }

  /**
   * Sends in Cowork: the same path as Code, but in the project folder, with the conversational
   * prompt and the reserved agent that keeps the session a chat-class session. See ADR-0013.
   */
  const sendCowork = (text: string, files: Attachment[], keepDraft = false) => {
    const directory = app.sessions.targetDirectory() ?? app.sessions.selectedSession()?.location?.directory
    if (!directory) {
      app.sessions.setError(t("Choose a project folder for Cowork"))
      return
    }
    submitPrompt(text, files, keepDraft, { agent: COWORK_AGENT, system: COWORK_SYSTEM })
  }

  /** Sends through the path the open view uses: a chat, a Cowork conversation, or Code. */
  const sendText = (text: string, files: Attachment[], keepDraft = false) => {
    if (!app.sessions.chatView()) return submitPrompt(text, files, keepDraft)
    return app.sessions.composerChatClass() === "cowork"
      ? sendCowork(text, files, keepDraft)
      : sendChat(text, files, keepDraft)
  }

  /** Resends the prompt that opened a failed turn, leaving whatever is typed in the composer alone. */
  const retryTurn = (messageID: string) => {
    const message = app.sessions.activeMessages()?.find((item) => item.id === messageID)
    if (message?.type !== "user") return
    const text = (message as { text?: string }).text ?? ""
    const files = ((message as { files?: Array<{ uri: string; name?: string }> }).files ?? []).map((file) => ({
      uri: file.uri,
      name: file.name ?? file.uri,
    }))
    sendText(text, files, true)
  }

  /**
   * Ask the open session to write down what it learned as a skill (H-43).
   *
   * The turn is visible on purpose: the session that did the work is the one that knows it, so the
   * agent writes `.opencode/skills/<name>/SKILL.md` with its own tools and the Skills screen reads
   * it back like any other. A chat has no project to write into, so it is told to use Code.
   */
  const skillifySession = (keepDraft = true) => {
    if (app.sessions.chatView()) {
      toast(t("Skills come from code sessions"), "info")
      return
    }
    if (!app.sessions.selected()) return
    submitPrompt(skillifyPrompt(), [], keepDraft)
  }

  /**
   * Writes down where the session stands. It is only a prompt, so it runs the same in Code, Chat and
   * Cowork — through the path each view already uses to send — and compacting the session stays on
   * `/compact`, which is the engine's job.
   */
  const resumeSession = (keepDraft = true) => {
    if (!app.sessions.selected()) {
      toast(t("No session"), "info")
      return
    }
    sendText(resumePrompt(), [], keepDraft)
  }

  /** What a built-in command is run with (TI-13), the same from the palette and the composer. */
  const commandContext = (): CommandContext => ({
    session: app.sessions.selected(),
    draft: prompt(),
    notify: (message) => toast(message, "info"),
    newSession: () => app.sessions.newSession(),
    go: app.router.go,
    send: (text) => sendText(text, attachments()),
    stash: (text) => stashPrompt(text, true),
    compact: app.sessions.compactSession,
    resume: () => resumeSession(),
    skillify: () => skillifySession(),
    toggleSteps: app.settings.toggleTools,
    toggleSidebar: app.settings.toggleSidebar,
    cycleTab: app.sessions.cycleSessionTab,
    closeTab: app.sessions.closeSessionTab,
    split: (session) => {
      if (!app.sessions.splitActive()) app.sessions.openSplit(session)
    },
    rename: app.sessions.renameSession,
    pin: app.sessions.togglePin,
    remove: app.sessions.deleteSession,
  })

  const send = () => {
    const text = prompt().trim()
    const files = attachments()
    if (!text && files.length === 0 && chips().length === 0) return
    recordPrompt(text)

    if (text.startsWith("/")) {
      const [rawName, ...rest] = text.slice(1).split(/\s+/)
      const name = rawName ?? ""
      const args = rest.join(" ").trim()
      // The built-ins first, so one runs the same here as from the palette (TI-13). The draft is the
      // command itself, so it is spent before the command runs.
      if (builtinCommand(name)) {
        setPrompt("")
        runBuiltin(name, args, commandContext())
        return
      }
      if (UNAVAILABLE_FEATURES.has(name)) {
        setPrompt("")
        toast(t("Coming soon"), "info")
        return
      }
      // A workflow belongs to a project, so it is launched in Code only; a chat has no workflows.
      const workflow = app.sessions.chatView() ? undefined : app.runs.workflowNamed(name)
      if (workflow) {
        app.runs.startWorkflow(workflow, args)
        return
      }
      // A chat has no engine commands or project skills: the built-ins have run by now, and what is
      // left is a message like any other, which is how a chat could always use `/anything`.
      if (app.sessions.chatView()) {
        return sendText(text, files)
      }
      const skill = app.catalog.skills()?.data?.find((item) => item.name === name)
      if (skill) {
        setPrompt("")
        void app.sessions.run(async (current) => {
          const sessionID = app.sessions.selected() ?? (await current.session.create()).id
          await current.session.skill({ sessionID, skill: skill.name })
          return sessionID
        })
        return
      }
      // The draft is spent the moment the command is run, like every built-in above clears it. Doing
      // it after the round trip left `/content list` sitting in the box while the engine answered, and
      // stuck there for good if the call failed.
      setPrompt("")
      void app.sessions.run(async (current) => {
        const model = selectedModel()
        const sessionID = app.sessions.selected() ?? (await current.session.create(model ? { model } : {})).id
        await current.session.command({ sessionID, command: name, ...(args ? { arguments: args } : {}) })
        return sessionID
      })
      return
    }

    if (app.sessions.chatView()) {
      return sendText(text, files)
    }

    if (text.startsWith("!")) {
      const command = text.slice(1).trim()
      if (!command) return
      void app.sessions.run(async (current) => {
        const sessionID = app.sessions.selected() ?? (await current.session.create()).id
        await current.session.shell({ sessionID, command })
        setPrompt("")
        return sessionID
      })
      return
    }

    submitPrompt(text, files)
  }
  return {
    addAttachments,
    agent,
    applyModel,
    attachments,
    changeAgent,
    changeDelivery,
    changeModel,
    changePermissionMode,
    changeVariant,
    collapsePaste,
    commandOptions,
    contextUsage,
    currentSuggestion,
    delivery,
    expandPastes,
    missingModel,
    missingModelReplacement,
    modelKey,
    modelLabel,
    modelName,
    modelRef,
    packRefs,
    packs,
    pendingModelSwitch,
    permissionModeId,
    pickModel,
    prompt,
    readAttachments,
    removeAttachment,
    chips,
    addChip: (chip: ContextChip) => addChips([chip]),
    addChips,
    removeChip: (id: string) => setChips((list) => list.filter((chip) => chip.id !== id)),
    removeStash,
    restoreStash,
    retryTurn,
    runCommand,
    savePack,
    searchFiles,
    selectedModel,
    send,
    sessionSpend,
    setAgent,
    setAttachments,
    setPackRefs,
    setPacks,
    setPendingModelSwitch,
    setPrompt,
    setStashes,
    setSuggestion,
    setSuggestionEffort,
    setSuggestionModel,
    stashPrompt,
    stashes,
    suggestionModel,
    suggestionVariant,
    suggestionVariants,
    suggestionsOn,
    toggleSuggestions,
    variantKey,
    variants,
  }
}

export type ComposerStore = ReturnType<typeof createComposer>
