/**
 * Every route the server answers that a phone may not use: each group in `api.ts` and the modules it
 * hands requests to, with each method. Config writes, workflow and routine edits, settings, pairing,
 * browser grants and the plugins' routes first, then everything else that is not reading a run.
 */
export const REFUSED = [
  // Config writes and the files they edit.
  ["PATCH", "/harness/engine-config"],
  ["GET", "/harness/engine-config"],
  ["PUT", "/harness/action-profiles/profile_1"],
  ["DELETE", "/harness/action-profiles/profile_1"],
  ["GET", "/harness/config-files"],
  ["GET", "/harness/config-files/read?path=/etc/hosts"],
  ["POST", "/harness/config-files/export"],
  ["POST", "/harness/agents"],
  ["DELETE", "/harness/agents?name=a"],
  ["GET", "/harness/agents"],
  ["POST", "/harness/skills"],
  ["DELETE", "/harness/skills?name=a"],
  ["GET", "/harness/skills"],
  ["GET", "/harness/skills/file?name=a"],
  ["POST", "/harness/commands"],
  ["DELETE", "/harness/commands?name=a"],
  ["GET", "/harness/commands"],
  // Workflows and routines, read or written.
  ["GET", "/harness/workflows"],
  ["GET", "/harness/workflows/ship"],
  ["GET", "/harness/workflows/ship/runs"],
  ["PUT", "/harness/workflows/ship"],
  ["DELETE", "/harness/workflows/ship"],
  ["POST", "/harness/workflows/ship/runs"],
  ["GET", "/harness/workflow-versions/ship"],
  ["GET", "/harness/routines"],
  ["POST", "/harness/routines"],
  ["GET", "/harness/routines/rt_1"],
  ["PATCH", "/harness/routines/rt_1"],
  ["PATCH", "/harness/routines/rt_1/enabled"],
  ["DELETE", "/harness/routines/rt_1"],
  ["GET", "/harness/routines/rt_1/runs"],
  ["POST", "/harness/routines/rt_1/runs"],
  ["POST", "/harness/routines/rt_1/runs/run_1/stop"],
  // Settings: the adaptive layer's, a project's unattended mode, budgets, what a reader keeps.
  ["GET", "/harness/adaptive/config"],
  ["PATCH", "/harness/adaptive/config"],
  ["GET", "/harness/adaptive/model-key"],
  ["PUT", "/harness/adaptive/model-key"],
  ["DELETE", "/harness/adaptive/model-key"],
  ["POST", "/harness/adaptive/runtime/acknowledge"],
  ["GET", "/harness/adaptive/capabilities"],
  ["GET", "/harness/adaptive/decisions"],
  ["GET", "/harness/adaptive/labels/coverage"],
  ["GET", "/harness/adaptive/voi"],
  ["GET", "/harness/adaptive/plans"],
  ["GET", "/harness/adaptive/proposals"],
  ["POST", "/harness/adaptive/proposals/p_1/approve"],
  ["GET", "/harness/adaptive/learned-skills"],
  ["POST", "/harness/adaptive/learned-skills/s_1/disable"],
  ["GET", "/harness/adaptive/sessions/ses_1"],
  ["PUT", "/harness/adaptive/sessions/ses_1"],
  ["POST", "/harness/adaptive/relevance"],
  ["POST", "/harness/adaptive/guardrails"],
  ["GET", "/harness/adaptive/guardrails/status"],
  ["GET", "/harness/adaptive/metrics"],
  ["POST", "/harness/adaptive/metrics"],
  ["POST", "/harness/adaptive/tool-trim"],
  ["POST", "/harness/adaptive/evidence"],
  ["GET", "/harness/adaptive/selection"],
  ["GET", "/harness/projects/unattended?directory=/tmp"],
  ["PUT", "/harness/projects/unattended"],
  ["GET", "/harness/budgets"],
  ["PUT", "/harness/budgets"],
  ["DELETE", "/harness/budgets/budget_1"],
  ["GET", "/harness/session-prefs"],
  ["PATCH", "/harness/session-prefs/ses_1"],
  ["GET", "/harness/stash"],
  ["POST", "/harness/stash"],
  ["DELETE", "/harness/stash/stash_1"],
  ["GET", "/harness/packs"],
  ["POST", "/harness/packs"],
  ["DELETE", "/harness/packs/pack_1"],
  ["GET", "/harness/memory?directory=/tmp"],
  ["POST", "/harness/memory"],
  ["DELETE", "/harness/memory/note_1"],
  // Pairing.
  ["POST", "/harness/pair"],
  ["POST", "/harness/pair/codes"],
  ["POST", "/harness/pair/refresh"],
  ["DELETE", "/harness/pair/tabs"],
  // Browser grants, the browser, web actions and stored credentials.
  ["GET", "/harness/browser-policy/grants"],
  ["DELETE", "/harness/browser-policy/grants/grant_1"],
  ["GET", "/harness/browser-policy/audit"],
  ["POST", "/harness/browser/start"],
  ["GET", "/harness/browser/session"],
  ["POST", "/harness/browser/stop"],
  ["GET", "/harness/browser/frame"],
  ["GET", "/harness/actions"],
  ["POST", "/harness/actions/run"],
  ["POST", "/harness/actions/validate"],
  ["GET", "/harness/credentials"],
  ["PUT", "/harness/credentials/cred_1"],
  ["DELETE", "/harness/credentials/cred_1"],
  // The engine plugins' routes.
  ["POST", "/harness/plan-exit"],
  ["POST", "/harness/browser-mcp/decide"],
  ["POST", "/harness/browser-mcp/observe"],
  ["POST", "/harness/usage/events"],
  ["POST", "/harness/artifacts/index"],
  // Starting, changing or forgetting work.
  ["POST", "/harness/runs"],
  ["DELETE", "/harness/runs"],
  ["POST", "/harness/runs/stop"],
  ["DELETE", "/harness/runs/run_1"],
  ["GET", "/harness/runs/run_1/resume"],
  ["POST", "/harness/runs/run_1/resume"],
  ["POST", "/harness/runs/run_1/worktrees/merge"],
  ["POST", "/harness/runs/run_1/worktrees/cleanup"],
  ["POST", "/harness/best-of-n"],
  ["POST", "/harness/tasks/task_1/retry"],
  ["POST", "/harness/tasks/task_1/cancel"],
  ["POST", "/harness/artifacts"],
  ["PATCH", "/harness/artifacts/art_1"],
  ["DELETE", "/harness/artifacts/art_1"],
  ["POST", "/harness/shares"],
  ["GET", "/harness/shares/share_1"],
  // The reader's machine: files, git, checkpoints, context, findings, usage beyond a run.
  ["GET", "/harness/files/read?directory=/tmp&path=a"],
  ["GET", "/harness/context?directory=/tmp"],
  ["GET", "/harness/context/file?directory=/tmp&path=AGENTS.md"],
  ["POST", "/harness/context/resolve"],
  ["GET", "/harness/context/system-prompt?sessionID=ses_1"],
  ["GET", "/harness/context/tool-uses?sessionID=ses_1"],
  ["GET", "/harness/findings"],
  ["PATCH", "/harness/findings/finding_1/resolved"],
  ["GET", "/harness/checkpoints?directory=/tmp"],
  ["POST", "/harness/checkpoints"],
  ["GET", "/harness/checkpoints/cp_1/plan"],
  ["POST", "/harness/checkpoints/cp_1/restore"],
  ["DELETE", "/harness/checkpoints/cp_1"],
  ["POST", "/harness/git/commit"],
  ["POST", "/harness/git/discard"],
  ["POST", "/harness/git/message"],
  ["POST", "/harness/git/branch"],
  ["GET", "/harness/git/branch?directory=/tmp"],
  ["GET", "/harness/git/pr?directory=/tmp"],
  ["GET", "/harness/git/pr/log?directory=/tmp&job=1"],
  ["POST", "/harness/git/pr"],
  ["GET", "/harness/usage/summary"],
  ["GET", "/harness/usage/sessions/ses_1"],
  // The allowed groups with a method or a depth they do not allow.
  ["DELETE", "/harness/events"],
  ["POST", "/harness/runs/run_1/approve/now"],
  ["PUT", "/harness/runs/run_1/stop"],
  ["GET", "/harness/runs/run_1/tasks/task_1"],
  ["GET", "/harness/artifacts/art_1/raw/more"],
  ["GET", "/harness/not-a-route"],
] as const
