name: containers

on:
  push:
    branches:
      - dev
    paths:
      - packages/containers/**
      - .github/workflows/containers.yml
      - package.json
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    env:
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      TAG: "24.04"
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v4.3.1

      - uses: ./.github/actions/setup-bun

      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v3.12.0

      - name: Login to GHCR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push containers
        run: bun ./packages/containers/script/build.ts --push
        env:
          REGISTRY: ${{ env.REGISTRY }}
          TAG: ${{ env.TAG }}
